# Build TurBoTse's kernal4.4 Padavan

name: build custom

on:
  workflow_dispatch:
    inputs:
      target:
        description: 'Select the router device'
        required: true
        type: choice
        options:
        - 360-T6M
        - 360-T6M-PB
        - B70
        - BELL-A040WQ
        - C-Life-XG1
        - CR660x
        - DIR-878
        - DIR-882
        - EA7500
        - G-AX1800
        - G-AX1800-B
        - GHL
        - HAR-20S2U1
        - JCG-836PRO
        - JCG-AC860M
        - JCG-Q10Pro
        - JCG-Q10Pro-PB
        - JCG-Q11Pro
        - JCG-Q20
        - JCG-Q20-PB
        - JCG-Y2
        - JDCLOUD-RE-CP-02
        - JDCLOUD-RE-SP-01B
        - K2P
        - K2P-NANO
        - K2P-USB
        - KOMI-A8
        - MI-4
        - MI-R3G
        - MI-R3P-PB
        - MI-R3P-SPI
        - MI-R3P
        - MI-R4A
        - MR2600
        - MSG1500
        - MSG1500-Z
        - NETGEAR-BZV
        - NETGEAR-R6800
        - NETGEAR-R7450
        - NEWIFI
        - NEWIFI3
        - QM-B1
        - R2100
        - RM2100
        - RT-AC85P
        - SIM-AX1800T
        - TX1801
        - WDR8620
        - WRL18M4GD
        - WE410443-TC
        - WIA3300-10
        - WR1200JS
        - XY-C1
        - ZTE-E8820S
        - ZTE-E8820V2
        - ZTT-RX6000
        default: K2P
      toolchain:
        description: 'Select the compilation toolchain'
        required: true
        type: choice
        options:
        - mipsel-linux-musl
        - mipsel-linux-uclibc
        default: mipsel-linux-musl
      toolchaingcc:
        description: 'Select the toolchain gcc version'
        required: true
        type: choice
        options:
        - mipsel-linux-musl
        - mipsel-linux-musl-gcc7
        - mipsel-linux-musl-gcc10
        - mipsel-linux-uclibc
        - mipsel-linux-uclibc-gcc7
        - mipsel-linux-uclibc-gcc10
        default: mipsel-linux-musl
      oldreleases:
        type: boolean
        description: 'Delete old releases'
        default: true
      oldworkflow:
        type: boolean
        description: 'Delete old workflow runs'
        default: true
env:
  FIRMWARE_AUTHOR: TurBoTse
  FIRMWARE_BRANCH: main
  FIRMWARE_URL: https://github.com/TurBoTse/padavan.git
  TOOLCHAIN_ROOT: toolchain/toolchain-mipsel
  TOOLCHAIN_URL: https://github.com/TurBoTse/padavan/releases/download/toolchain
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: hendrikmuhs/ccache-action@main
        with:
          key: ${{ inputs.target }}-${{ inputs.toolchaingcc }}
      - uses: actions/setup-go@main
        with:
          go-version: '1.23.5'
          check-latest: true
          cache: false
      - name: Prepare environment
        run: |
          sudo apt-get update && sudo apt-get install -y unzip libtool-bin ccache curl cmake gperf gawk flex bison nano xxd \
            fakeroot kmod cpio bc zip git python3-docutils gettext automake autopoint \
            texinfo build-essential help2man pkg-config zlib1g-dev libgmp3-dev \
            libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev wget libc-dev-bin liblzma-dev
          echo "TRUNK_DIR=${{ github.workspace }}/padavan/trunk" >> $GITHUB_ENV
          echo "Compilation_time=$(TZ='Asia/Shanghai' date +%Y%m%d)" >> $GITHUB_ENV

      - name: Download sources and toolchain
        run: |
          git clone -b $FIRMWARE_BRANCH --depth=1 $FIRMWARE_URL padavan
          mkdir -p padavan/$TOOLCHAIN_ROOT
          curl -fSsLo- $TOOLCHAIN_URL/${{ inputs.toolchaingcc }}.tar.xz | tar Jxv -C padavan/$TOOLCHAIN_ROOT

      - name: Modify and customize
        run: |
          sed -i '/cp -f/d' padavan/Makefile
          if [ -f ${{ inputs.target }}.config ]; then
            mv -fv ${{ inputs.target }}.config ${{ env.TRUNK_DIR }}/configs/templates/${{ inputs.target }}.config
          fi
          cd ${{ env.TRUNK_DIR }}
          cp -f configs/templates/${{ inputs.target }}.config /.config

      - name: Start build firmware
        run: |
          cd padavan
          make ${{ inputs.target }} TOOLCHAIN=${{ inputs.toolchain }}
          mkdir -p ${{ env.TRUNK_DIR }}/firmwares/
          sudo mv ${{ env.TRUNK_DIR }}/images/*.trx ${{ env.TRUNK_DIR }}/firmwares/$FIRMWARE_AUTHOR-${{ inputs.target }}-4.4-${{ inputs.toolchaingcc }}-${{ env.Compilation_time }}.trx

      - uses: actions/upload-artifact@main
        with:
          name: ${{ inputs.target }}-${{ inputs.toolchaingcc }}
          path: ${{ env.TRUNK_DIR }}/firmwares/*.trx

      - uses: ncipollo/release-action@main
        with:
          commit: main
          tag: ${{ env.Compilation_time }}
          artifacts: ${{ env.TRUNK_DIR }}/firmwares/*.trx
          allowUpdates: true
          omitBodyDuringUpdate: true
 
      - uses: dev-drprasad/delete-older-releases@master
        if: ${{ github.event.inputs.oldreleases == 'true' }}
        with:
          keep_latest: 1
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: Mattraks/delete-workflow-runs@main
        if: ${{ github.event.inputs.oldworkflow == 'true' }}
        with:
          retain_days: 0
          keep_minimum_runs: 1
